FROM python:3.12-slim-bullseye
WORKDIR /app

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Copy everything
COPY . /app

# Install Flask and Sherlock project
RUN pip install --no-cache-dir flask
RUN pip install --no-cache-dir .

# Expose port
EXPOSE 9900

# Run the web app
ENTRYPOINT ["python", "web_app.py"]
